# version: '3'
# services:
#   web:
#     build: .
#     ports:
#       - "8090:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       # - ./www:/usr/share/nginx/html/
# version: '3'
# services:
#   nginx:
#     image: nginx:latest
#     environment:
#       - BLUE_SERVER=${BLUE_SERVER}
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./www:/usr/share/nginx/html
#     ports:
#       - "80:80"
#     restart: always

version: '3'
services:
  serverproxy:
    image: nginx:latest
    container_name: serverproxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/usr/share/nginx/html
      - ./log/nginx/access.log:/var/log/nginx/access.log;
      - ./log/nginx/error.log:/var/log/nginx/error.log;
      # - ./lpdocs.template:/etc/nginx/conf.d/lpdocs.template
    restart: always
    #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/lpdocs.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'" 